=== Arun-2208/Semester_1_CodeWork_and_CourseWork/COS 60009 - Data Management for the Big Data Age/dtd/company.dtd
<!DOCTYPE Company [
        <!ELEMENT Company (Division+)>
        <!ELEMENT Division (DNAME, LOCATION, Projects, Employees)>
        <!ATTLIST Division DID CDATA #REQUIRED>
        <!ELEMENT DNAME (#PCDATA)>
        <!ELEMENT LOCATION (#PCDATA)>
        <!ELEMENT Projects (Project+)>
        <!ELEMENT Project (PNAME, BUDGET, Assign+)>
        <!ATTLIST Project PID CDATA #REQUIRED>
        <!ATTLIST Project DID CDATA #REQUIRED>
        <!ELEMENT PNAME (#PCDATA)>
        <!ELEMENT BUDGET (#PCDATA)>
        <!ELEMENT Assign (HOURS)>
        <!ATTLIST Assign PID CDATA #REQUIRED>
        <!ATTLIST Assign EID CDATA #REQUIRED>
        <!ELEMENT HOURS (#PCDATA)>
        <!ELEMENT Employees (Employee+)>
        <!ELEMENT Employee (ENAME, OFFICE, BIRTHDATE, SALARY)>
        <!ATTLIST Employee EID CDATA #REQUIRED>
        <!ATTLIST Employee DID CDATA #REQUIRED>
        <!ELEMENT ENAME (#PCDATA)>
        <!ELEMENT OFFICE (#PCDATA)>
        <!ELEMENT BIRTHDATE (#PCDATA)>
        <!ELEMENT SALARY (#PCDATA)>
]>

=== Arun-2208/Semester_1_CodeWork_and_CourseWork/COS 60009 - Data Management for the Big Data Age/dtd/company.xml
<?xml version="1.0" encoding="utf-8" dependency="yes"?>
<!DOCTYPE Company SYSTEM "company.dtd">
<Company>
    <Division DID="T01">
        <DNAME>Technology</DNAME>
        <LOCATION>Sydney</LOCATION>
        <Projects>
            <Project PID="P001" DID="T01">
                <PNAME>Software Development Engineering</PNAME>
                <BUDGET>2000000</BUDGET>
                <Assign PID="P001" EID="EMP001">
                    <HOURS>2000</HOURS>
                </Assign>
                <Assign PID="P001" EID="EMP002">
                    <HOURS>2500</HOURS>
                </Assign>
            </Project>
            <Project PID="P002" DID="T01">
                <PNAME>Devops Engineering</PNAME>
                <BUDGET>2500000</BUDGET>
                <Assign PID="P002" EID="EMP002">
                    <HOURS>20</HOURS>
                </Assign>
                <Assign PID="P002" EID="EMP003">
                    <HOURS>20</HOURS>
                </Assign>
            </Project>
        </Projects>
        <Employees>
            <Employee EID="EMP001" DID="T01">
                <ENAME>Arun Ragavendhar</ENAME>
                <OFFICE>101</OFFICE>
                <BIRTHDATE>1999-08-22</BIRTHDATE>
                <SALARY>120000</SALARY>
            </Employee>
            <Employee EID="EMP002" DID="T01">
                <ENAME>Christopher Opie</ENAME>
                <OFFICE>102</OFFICE>
                <BIRTHDATE>1985-01-01</BIRTHDATE>
                <SALARY>150000</SALARY>
            </Employee>
            <Employee EID="EMP003" DID="T01">
                <ENAME>Landy Wang</ENAME>
                <OFFICE>103</OFFICE>
                <BIRTHDATE>1996-06-04</BIRTHDATE>
                <SALARY>130000</SALARY>
            </Employee>
        </Employees>
    </Division>
    
    <Division DID="M01">
        <DNAME>Marketing</DNAME>
        <LOCATION>Melbourne</LOCATION>
        <Projects>
            <Project PID="P003" DID="M01">
                <PNAME>Brand Promotion</PNAME>
                <BUDGET>1800000</BUDGET>
                <Assign PID="P003" EID="EMP004">
                    <HOURS>20</HOURS>
                </Assign>
                <Assign PID="P003" EID="EMP005">
                    <HOURS>20</HOURS>
                </Assign>
            </Project>
            <Project PID="P004" DID="M01">
                <PNAME>Market Research</PNAME>
                <BUDGET>2200000</BUDGET>
                <Assign PID="P004" EID="EMP005">
                    <HOURS>20</HOURS>
                </Assign>
                <Assign PID="P004" EID="EMP006">
                    <HOURS>20</HOURS>
                </Assign>
            </Project>
        </Projects>
        <Employees>
            <Employee EID="EMP004" DID="M01">
                <ENAME>Emma Watson</ENAME>
                <OFFICE>304</OFFICE>
                <BIRTHDATE>1988-05-15</BIRTHDATE>
                <SALARY>140000</SALARY>
            </Employee>
            <Employee EID="EMP005" DID="M01">
                <ENAME>David Warner</ENAME>
                <OFFICE>401</OFFICE>
                <BIRTHDATE>1979-09-30</BIRTHDATE>
                <SALARY>160000</SALARY>
            </Employee>
            <Employee EID="EMP006" DID="M01">
                <ENAME>Harry Potter</ENAME>
                <OFFICE>206</OFFICE>
                <BIRTHDATE>1992-11-18</BIRTHDATE>
                <SALARY>130000</SALARY>
            </Employee>
        </Employees>
    </Division>
</Company>
